# Support PaperKnife Development
github: potatameister

# Message:
# I am the developer of PaperKnife. In my daily life, I work a full-time 
# job (50 hours a week) for a monthly income of US$150. I build 
# open-source software like PaperKnife for free because I believe in 
# digital privacy, but balancing this with my financial reality is difficult.
#
# Your support would help me manage my living expenses and fund the 
# one-time Google Play and Apple Developer fees. This will allow me to 
# bring PaperKnife to official app stores and reach more users. 
#
# Every donation helps me keep building for the community. Thank you 
# for supporting independent, open-source work.
